name: Update Commit Hash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get commit hash
        id: commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update commit hash
        run: echo -n "${{ env.commit_hash }}" > commit_hash.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update commit hash
          file_pattern: commit_hash.txt
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          branch: main
